name: Build macOS DMG (Intel + Apple Silicon)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  build:
    runs-on: macos-13  # Intel runner - Ventura
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Download NLTK data
      run: |
        python -c "import nltk; nltk.download('punkt'); nltk.download('punkt_tab'); nltk.download('stopwords'); nltk.download('wordnet')"
    
    - name: Build executable
      run: |
        python build_executable.py
    
    - name: Check build output structure
      run: |
        echo "Contents of dist folder:"
        ls -la dist/
        echo "Contents of SentimentAnalysisTool folder:"
        ls -la dist/SentimentAnalysisTool/ || echo "Folder not found"
    
    - name: Ad-hoc sign the app
      run: |
        # Find and sign the actual app
        if [ -f "dist/SentimentAnalysisTool.app/Contents/MacOS/SentimentAnalysisTool" ]; then
          codesign --force --deep --sign - "dist/SentimentAnalysisTool.app"
        elif [ -f "dist/SentimentAnalysisTool/SentimentAnalysisTool" ]; then
          # Sign the executable if no .app bundle
          codesign --force --sign - "dist/SentimentAnalysisTool/SentimentAnalysisTool"
        fi
    
    - name: Create ZIP archive
      run: |
        cd dist
        zip -r ../SentimentAnalysisTool-macOS-Intel.zip SentimentAnalysisTool
        cd ..
        echo "Created ZIP archive"
    
    - name: Upload ZIP
      uses: actions/upload-artifact@v4
      with:
        name: SentimentAnalysisTool-macOS-Intel
        path: SentimentAnalysisTool-macOS-Intel.zip
        retention-days: 30
    
    - name: Create Release (on tag push)
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: SentimentAnalysisTool-macOS-Intel.zip
        draft: false
        prerelease: false